version: '2'
services:
  repo:
    image: docker-internal.alfresco.com/platform:latest
    environment:
         JAVA_OPTS : "-Dsolr.useDynamicShardRegistration=false
         -Dsolr.host=solr6  -Dsolr.port.ssl=8084 -Dsolr.secureComms=https
         -Dsolr.base.url=/solr -Dindex.subsystem.name=solr6"
    ports:
          - "7203:7203" #JMX connect via service:jmx:rmi:///jndi/rmi://localhost:7203/jmxrmi
          - "5005:5005" #Java debugging
          - "8082:8080" #Browser port
  share:
    image: docker-internal.alfresco.com/share:5.2.1-demo
    ports:
      - "8081:8080"
    environment:
      - "REPO_HOST=repo:8080"
  solr6:
    image: docker-internal.alfresco.com/search-services:develop-latest
    command: [ "/opt/alfresco-solr/solr/bin/solr", "start", "-f", "-p","8084", "-a",
               "-Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=1044"]
    expose:
     - "8084"
    environment:
      #Solr needs to know how to register itself with Alfresco
      SOLR_ALFRESCO_HOST: repo
      SOLR_ALFRESCO_PORT: 8080
      #Alfresco needs to know how to call solr
      SOLR_SOLR_HOST: solr6
      SOLR_SOLR_PORT: 8084

      #Create the default alfresco and archive cores
      #SOLR_CREATE_ALFRESCO_DEFAULTS : alfresco,archive

      #SOLR_OPTS: "$SOLR_OPTS -Djavax.net.debug=SSL,keymanager,trustmanager"
      #SOLR_SSL_KEY_STORE: /opt/alfresco/alf_data/keystore/ssl.repo.client.keystore
      #SOLR_SSL_KEY_STORE_PASSWORD: kT9X6oe68t
      #SOLR_SSL_TRUST_STORE: /opt/alfresco/alf_data/keystore/ssl.repo.client.truststore
      #SOLR_SSL_TRUST_STORE_PASSWORD: kT9X6oe68t

    ports:
      - "8084:8084" #Browser port
      - "1044:1044" #Java debugging
    volumes_from:
     - repo:ro

#docker-compose -f compose-ssl.yml up
#Bash to Alfresco instance: docker exec -it [containerid] bash
# cd /opt/alfresco/alf_data/keystore
# chmod +x generate_keystores.sh
# ./generate_keystores.sh
# cp ~/ssl.repo.client.keystore /opt/alfresco/alf_data/keystore/
# cp ~/ssl.repo.client.truststore /opt/alfresco/alf_data/keystore/
#Bash to Solr instance: docker exec -it [containerid] bash
# cd /opt/alfresco-solr/solrhome/templates/rerank/conf
# rm ssl.repo.client.truststore
# rm ssl.repo.client.keystore
# cp /opt/alfresco/alf_data/keystore/ssl.repo.client.keystore .
# cp /opt/alfresco/alf_data/keystore/ssl.repo.client.truststore .
# edit solrhome/templates/rerank/conf/solrcore.properties and set alfresco.secureComms=https
# Uncomment the SSL setup config (above) and uncomment the SOLR_CREATE_ALFRESCO_DEFAULTS
# Stop and restart