version: '3'
services:
  alfresco:
      image: quay.io/alfresco/alfresco-full-content-services:${ALFRESCO_TAG}
      environment:
          JAVA_OPTS : "
              -Ddb.driver=org.postgresql.Driver
              -Ddb.username=alfresco
              -Ddb.password=alfresco
              -Ddb.url=jdbc:postgresql://postgres:5432/alfresco
              -Dsolr.host=search
              -Dsolr.port=8983
              -Dsolr.secureComms=none
              -Dsolr.base.url=/solr
              -Dindex.subsystem.name=solr6
              -Dalfresco.restApi.basicAuthScheme=true
              -Dimap.server.enabled=true
              -Dftp.enabled=true
              -Dftp.dataPortFrom=30000
              -Dftp.dataPortTo=30099
              "
      ports:
          - "7203:7203" #JMX connect via service:jmx:rmi:///jndi/rmi://localhost:7203/jmxrmi
          - "5005:5005" #Java debugging
          - "8081:8080" #Browser port for Alfresco
#          - "445:445"
          - "143:143"
          - "21:21"
          - "30000-30099:30000-30099"

  share:
      image: quay.io/alfresco/alfresco-full-share:${SHARE_TAG}
      environment:
          - REPO_HOST=alfresco
          - REPO_PORT=8080
      ports:
            - 8082:8080 #Browser port for Share

  postgres:
      image: docker.io/library/postgres:9.4.12
      environment:
          - POSTGRES_PASSWORD=alfresco
          - POSTGRES_USER=alfresco
          - POSTGRES_DB=alfresco
      ports:
          - 5432:5432

  search:
    image: quay.io/alfresco/search-services:${project.version}
    environment:
        #Solr needs to know how to register itself with Alfresco
        - SOLR_ALFRESCO_HOST=alfresco
        - SOLR_ALFRESCO_PORT=8080
        #Alfresco needs to know how to call solr
        - SOLR_SOLR_HOST=search
        - SOLR_SOLR_PORT=8983
        #Create the default alfresco and archive cores
        - SOLR_CREATE_ALFRESCO_DEFAULTS=alfresco,archive
    ports:
        - 8083:8983 #Browser port