os: linux
dist: xenial
language: java
jdk:
  - openjdk11

services:
  - docker

cache:
  directories:
    - $HOME/.m2
# the cache can grow constantly
before_cache:
  - rm -rf $HOME/.m2/repository/org/alfresco/*

branches:
  only:
    - master
    - /release\/.*/

stages:
  - name: Tests
    if: commit_message !~ /\[skip tests\]/
  - Deploy
  - Release
  - Publish

env:
  global:
    # Release version has to start with real version (2.0.0-....) for the docker image to build successfully.
    - RELEASE_VERSION=2.0.0-A3
    - DEVELOPMENT_VERSION=2.0.0-SNAPSHOT

# This should not be required on community build
before_install:
  - "cp .travis.settings.xml $HOME/.m2/settings.xml"

jobs:
  include:
    - stage: Tests
      name: "Unit tests"
      jdk: openjdk11
      install:
        - travis_retry travis_wait 60 mvn --batch-mode -q clean package -DskipTests
      script:
        - travis_wait 60 mvn --batch-mode package -DfailIfNoTests=false -Dtests.timezone=UTC -Dmaven.test.failure.ignore=true -pl '"!:search-analytics-e2e-test"'
    - name: "CMIS API tests"
      jdk: openjdk11
      install:
        - travis_retry travis_wait 60 mvn --batch-mode -q clean package -DskipTests
        - docker login quay.io -u ${QUAY_USERNAME} -p ${QUAY_PASSWORD}
        - travis_retry travis_wait 40 docker build -t quay.io/alfresco/insight-engine:latest insight-engine/packaging/target/docker-resources
        - mkdir -p e2e-test/target/docker-resources && python e2e-test/python-generator/generator.py --alfresco=quay.io/alfresco/dev:acs-for-search --transformer=LegacyTransformers --search=quay.io/alfresco/insight-engine:latest --spellcheck --output=e2e-test/target/docker-resources
        - ./e2e-test/helpers/start-alfresco.sh "e2e-test/target/docker-resources" "quay.io/alfresco/insight-engine:latest"
        - ./e2e-test/helpers/wait-service-to-start.sh
      script:
        - travis_wait 60 mvn test -f e2e-test/pom.xml -DsuiteXmlFile=src/test/resources/cmis-search.xml -Dtest.exclude=Not_InsightEngine,CONFIG_Master_Slave,Not_Bamboo,AGS_302,CONFIG_Sharding_DB_ID_RANGE,CONFIG_Sharding -Dalfresco.server=localhost -Dalfresco.port=8081 -Dmaven.test.failure.ignore=true
    - name: "SEARCH API tests"
      jdk: openjdk11
      install:
        - travis_retry travis_wait 60 mvn --batch-mode -q clean package -DskipTests
        - docker login quay.io -u ${QUAY_USERNAME} -p ${QUAY_PASSWORD}
        - travis_retry travis_wait 40 docker build -t quay.io/alfresco/insight-engine:latest insight-engine/packaging/target/docker-resources
        - mkdir -p e2e-test/target/docker-resources && python e2e-test/python-generator/generator.py --alfresco=quay.io/alfresco/dev:acs-for-search --transformer=LegacyTransformers --search=quay.io/alfresco/insight-engine:latest --spellcheck --output=e2e-test/target/docker-resources
        - ./e2e-test/helpers/start-alfresco.sh "e2e-test/target/docker-resources" "quay.io/alfresco/insight-engine:latest"
        - ./e2e-test/helpers/wait-service-to-start.sh
      script:
        - travis_wait 60 mvn test -f e2e-test/pom.xml -DsuiteXmlFile=src/test/resources/SearchSuite.xml -Dtest.exclude=Not_InsightEngine,CONFIG_Master_Slave,Not_Bamboo,AGS_302,CONFIG_Sharding_DB_ID_RANGE,CONFIG_Sharding -Dalfresco.server=localhost -Dalfresco.port=8081 -Dmaven.test.failure.ignore=true
    - name: "SQL API tests"
      jdk: openjdk11
      install:
        - travis_retry travis_wait 60 mvn --batch-mode -q clean package -DskipTests
        - docker login quay.io -u ${QUAY_USERNAME} -p ${QUAY_PASSWORD}
        - travis_retry travis_wait 40 docker build -t quay.io/alfresco/insight-engine:latest insight-engine/packaging/target/docker-resources
        - mkdir -p e2e-test/target/docker-resources && python e2e-test/python-generator/generator.py --alfresco=quay.io/alfresco/dev:acs-for-search --transformer=LegacyTransformers --search=quay.io/alfresco/insight-engine:latest --spellcheck --output=e2e-test/target/docker-resources
        - ./e2e-test/helpers/start-alfresco.sh "e2e-test/target/docker-resources" "quay.io/alfresco/insight-engine:latest"
        - ./e2e-test/helpers/wait-service-to-start.sh
      script:
        - travis_wait 60 mvn test -f e2e-test/pom.xml -DsuiteXmlFile=src/test/resources/InsightSuite.xml -Dtest.exclude=Not_InsightEngine,CONFIG_Master_Slave,Not_Bamboo,AGS_302,CONFIG_Sharding_DB_ID_RANGE,CONFIG_Sharding -Dalfresco.server=localhost -Dalfresco.port=8081 -Dmaven.test.failure.ignore=true
    - name: "Integration tests"
      jdk: openjdk11
      install:
        - travis_retry travis_wait 60 mvn --batch-mode -q clean package -DskipTests
      script:
        - travis_wait 60 mvn -q verify -Dtest=foo -DfailIfNoTests=false -Dtests.timezone=UTC -Dmaven.test.failure.ignore=true -pl '"!:search-analytics-e2e-test"'
    - name: "Build and verify Docker images"
      jdk: openjdk11
      install:
        - travis_retry travis_wait 60 mvn --batch-mode -q clean package -DskipTests
        - docker login quay.io -u ${QUAY_USERNAME} -p ${QUAY_PASSWORD}
        - travis_retry travis_wait 40 docker build -t quay.io/alfresco/search-services:latest search-services/packaging/target/docker-resources
        - travis_retry travis_wait 40 docker build -t quay.io/alfresco/insight-engine:latest insight-engine/packaging/target/docker-resources
        - travis_retry travis_wait 40 docker build -t quay.io/alfresco/insight-zeppelin:latest insight-engine/alfresco-insight-zeppelin/target/docker-resources
      script:
        - travis_wait 60 ./scripts/test-image.sh "${TRAVIS_BUILD_DIR}" "search-services/packaging/target/docker-resources insight-engine/packaging/target/docker-resources insight-engine/alfresco-insight-zeppelin/target/docker-resources" "quay.io/alfresco/search-services quay.io/alfresco/insight-engine quay.io/alfresco/insight-zeppelin" "latest" "alfresco-search-services alfresco-insight-engine zeppelin"
    - name: "Whitesource scan - Search Services"
      #TODO run only on release branches and master
      #if: fork = false AND (branch = master OR branch =~ /release\/.*/) AND type != pull_request
      jdk: openjdk11
      install:
        - travis_retry travis_wait 60 mvn --batch-mode -q clean package -DskipTests
        - mkdir -p whitesource_scan/search-services && unzip search-services/packaging/target/*.zip -d whitesource_scan/search-services
      script:
        - curl -LJO https://github.com/whitesource/unified-agent-distribution/releases/latest/download/wss-unified-agent.jar
        - java -jar wss-unified-agent.jar -apiKey ${WHITESOURCE_API_KEY} -project "SearchServices" -projectVersion "2.0.0-SNAPSHOT" -d ./whitesource_scan/search-services
    - name: "Whitesource scan - Insight Engine"
      #TODO run only on release branches and master
      #if: fork = false AND (branch = master OR branch =~ /release\/.*/) AND type != pull_request
      jdk: openjdk11
      install:
        - travis_retry travis_wait 60 mvn --batch-mode -q clean package -DskipTests
        - mkdir -p whitesource_scan/insight-engine && unzip insight-engine/packaging/target/*.zip -d whitesource_scan/insight-engine
      script:
        - curl -LJO https://github.com/whitesource/unified-agent-distribution/releases/latest/download/wss-unified-agent.jar
        - java -jar wss-unified-agent.jar -apiKey ${WHITESOURCE_API_KEY} -project "InsightEngine" -projectVersion "2.0.0-SNAPSHOT" -d ./whitesource_scan/insight-engine
    - name: "Whitesource scan - Zeppelin"
      #TODO run only on release branches and master
      #if: fork = false AND (branch = master OR branch =~ /release\/.*/) AND type != pull_request
      jdk: openjdk11
      install:
        - travis_retry travis_wait 60 mvn --batch-mode -q clean package -DskipTests
        - mkdir -p whitesource_scan/insight-zeppelin && unzip insight-engine/alfresco-insight-zeppelin/target/*.zip -d whitesource_scan/insight-zeppelin
      script:
        - curl -LJO https://github.com/whitesource/unified-agent-distribution/releases/latest/download/wss-unified-agent.jar
        - java -jar wss-unified-agent.jar -apiKey ${WHITESOURCE_API_KEY} -project "InsightZeppelin" -projectVersion "2.0.0-SNAPSHOT" -d ./whitesource_scan/insight-zeppelin
    - stage: Deploy
      name: Deploy snapshots to Nexus
      #TODO run only on release branches and master
      #if: fork = false AND (branch = master OR branch =~ /release\/.*/) AND type != pull_request
      install:
        - travis_retry travis_wait 60 mvn --batch-mode -q clean package -DskipTests
      script:
        - travis_wait 60 mvn --batch-mode deploy -DskipTests=true
    - name: Deploy dev version to quay.io
      #TODO run only on release branches
      #if: fork = false AND ( branch =~ /release\/.*/) AND type != pull_request
      install:
        - travis_retry travis_wait 60 mvn --batch-mode -q clean package -DskipTests
        - docker login quay.io -u ${QUAY_USERNAME} -p ${QUAY_PASSWORD}
        - travis_retry travis_wait 40 docker build -t quay.io/alfresco/search-services:$DEVELOPMENT_VERSION search-services/packaging/target/docker-resources
        - travis_retry travis_wait 40 docker build -t quay.io/alfresco/insight-engine:$DEVELOPMENT_VERSION insight-engine/packaging/target/docker-resources
        - travis_retry travis_wait 40 docker build -t quay.io/alfresco/insight-zeppelin:$DEVELOPMENT_VERSION insight-engine/alfresco-insight-zeppelin/target/docker-resources
      script:
        - travis_retry docker push quay.io/alfresco/search-services:$DEVELOPMENT_VERSION
        - travis_retry docker push quay.io/alfresco/insight-engine:$DEVELOPMENT_VERSION
        - travis_retry docker push quay.io/alfresco/insight-zeppelin:$DEVELOPMENT_VERSION
    - name: Deploy "latest" to quay.io
      #TODO run only on master
      #if: fork = false AND (branch = master) AND type != pull_request
      install:
        - travis_retry travis_wait 60 mvn --batch-mode -q clean package -DskipTests
        - docker login quay.io -u ${QUAY_USERNAME} -p ${QUAY_PASSWORD}
        - travis_retry travis_wait 40 docker build -t quay.io/alfresco/search-services:latest search-services/packaging/target/docker-resources
        - travis_retry travis_wait 40 docker build -t quay.io/alfresco/insight-engine:latest insight-engine/packaging/target/docker-resources
        - travis_retry travis_wait 40 docker build -t quay.io/alfresco/insight-zeppelin:latest insight-engine/alfresco-insight-zeppelin/target/docker-resources
      script:
        - travis_retry docker push quay.io/alfresco/search-services:latest
        - travis_retry docker push quay.io/alfresco/insight-engine:latest
        - travis_retry docker push quay.io/alfresco/insight-zeppelin:latest
    - name: "Release and Copy to S3 Staging Bucket"
      stage: Release
      # TODO release only on releasable branches and if the commit has "release" keyword
#      if: fork = false AND (branch = master OR branch =~ /support\/.*/) AND type != pull_request AND commit_message =~ /\[release\]/
#      if: commit_message =~ /\[release\]/
      install:
        - travis_retry travis_wait 60 mvn --batch-mode -q clean package -DskipTests
      script:
        - travis_wait 60 mvn --batch-mode -DreleaseVersion=$RELEASE_VERSION -DdevelopmentVersion=$DEVELOPMENT_VERSION release:prepare release:perform -DskipTests "-Darguments=-DskipTests -Dadditionalparam=-Xdoclint:none"
      deploy:
        - provider: s3
          access_key_id: ${AWS_STAGING_ACCESS_KEY}
          secret_access_key: ${AWS_STAGING_SECRET_KEY}
          region: "eu-west-1"
          bucket: "alfresco-artefacts-staging"
          glob: "alfresco-search-services-${RELEASE_VERSION}.zip"
          upload_dir: "enterprise/SearchServices/${RELEASE_VERSION}"
          skip_cleanup: true
          acl: private
          local_dir: "search-services/packaging/target"
        - provider: s3
          access_key_id: ${AWS_STAGING_ACCESS_KEY}
          secret_access_key: ${AWS_STAGING_SECRET_KEY}
          region: "eu-west-1"
          bucket: "alfresco-artefacts-staging"
          glob: "alfresco-insight-engine-distribution-${RELEASE_VERSION}.zip"
          upload_dir: "enterprise/InsightEngine/${RELEASE_VERSION}"
          skip_cleanup: true
          acl: private
          local_dir: "insight-engine/packaging/target"
        - provider: s3
          access_key_id: ${AWS_STAGING_ACCESS_KEY}
          secret_access_key: ${AWS_STAGING_SECRET_KEY}
          region: "eu-west-1"
          bucket: "alfresco-artefacts-staging"
          glob: "alfresco-insight-zeppelin-${RELEASE_VERSION}.zip"
          upload_dir: "enterprise/InsightZeppelin/${RELEASE_VERSION}"
          skip_cleanup: true
          acl: private
          local_dir: "insight-engine/alfresco-insight-zeppelin/target"
    - name: Deploy release version to quay.io
      #TODO run only on release branches and if the commit has "release" keyword
      #if: fork = false AND ( branch =~ /release\/.*/) AND type != pull_request
      #if: commit_message =~ /\[release\]/
      install:
        - travis_retry travis_wait 60 mvn --batch-mode -q clean package -DskipTests
        - docker login quay.io -u ${QUAY_USERNAME} -p ${QUAY_PASSWORD}
        - travis_retry travis_wait 40 docker build -t quay.io/alfresco/search-services:$RELEASE_VERSION search-services/packaging/target/docker-resources
        - travis_retry travis_wait 40 docker build -t quay.io/alfresco/insight-engine:$RELEASE_VERSION insight-engine/packaging/target/docker-resources
        - travis_retry travis_wait 40 docker build -t quay.io/alfresco/insight-zeppelin:$RELEASE_VERSION insight-engine/alfresco-insight-zeppelin/target/docker-resources
      script:
        - travis_retry docker push quay.io/alfresco/search-services:$RELEASE_VERSION
        - travis_retry docker push quay.io/alfresco/insight-engine:$RELEASE_VERSION
        - travis_retry docker push quay.io/alfresco/insight-zeppelin:$RELEASE_VERSION