os: linux
dist: xenial
sudo: required
language: java
jdk:
  - openjdk11

services:
  - docker

cache:
  directories:
    - $HOME/.m2
# the cache can grow constantly
before_cache:
  - rm -rf $HOME/.m2/repository/org/alfresco/*

#branches:
#  only:
#    - master
#    - /release\/.*/

stages:
  - name: test
    if: commit_message !~ /\[skip tests\]/
  - release
  - publish

# This should not be required on community build
before_install:
  - "cp .travis.settings.xml $HOME/.m2/settings.xml"

jobs:
  include:
    - stage: test
      name: "Unit tests"
      jdk: openjdk11
      install:
        - travis_retry travis_wait 40 mvn --batch-mode clean package -DskipTests
      script:
        - travis_wait 60 mvn --batch-mode package -DfailIfNoTests=false -Dmaven.wagon.http.pool=false -Dtests.timezone=UTC -Dmaven.test.failure.ignore=true -pl '"!:search-analytics-e2e-test"'


