version: '3'
services:
  alfresco:
    image: ${ALFRESCO_IMAGE}:${ALFRESCO_TAG}
    environment:
      JAVA_OPTS : "
        -Ddb.driver=org.postgresql.Driver
        -Ddb.username=alfresco
        -Ddb.password=alfresco
        -Ddb.url=jdbc:postgresql://postgres:5432/alfresco
        -Dsolr.host=search
        -Dsolr.port=80
        -Dsolr.secureComms=none
        -Dsolr.base.url=/solr
        -Dindex.subsystem.name=solr6
        -Dalfresco.restApi.basicAuthScheme=true
        -Ddeployment.method=DOCKER_COMPOSE
        -Dcsrf.filter.enabled=false
        -Dmessaging.broker.url=\"failover:(nio://activemq:61616)?timeout=3000&jms.useCompression=true\"
        "
    ports:
      - "7203:7203" #JMX connect via service:jmx:rmi:///jndi/rmi://localhost:7203/jmxrmi
      - "5005:5005" #Java debugging
      - "8081:8080" #Browser port for Alfresco

  share:
    image: ${SHARE_IMAGE}:${SHARE_TAG}
    environment:
      - REPO_HOST=alfresco
      - REPO_PORT=8080
    ports:
      - 8082:8080 #Browser port for Share

  postgres:
    image: ${POSTGRES_IMAGE}:${POSTGRES_TAG}
    environment:
      - POSTGRES_PASSWORD=alfresco
      - POSTGRES_USER=alfresco
      - POSTGRES_DB=alfresco
    ports:
      - 5432:5432

  search:
    image: dockercloud/haproxy
    links:
      - solr
    ports:
      - 8083:80 #Browser port
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  solr:
    image: ${SEARCH_IMAGE}:${SEARCH_TAG}
    environment:
      #Solr needs to know how to register itself with Alfresco
      - SOLR_ALFRESCO_HOST=alfresco
      - SOLR_ALFRESCO_PORT=8080
      #Alfresco needs to know how to call solr
      - SOLR_SOLR_HOST=search
      - SOLR_SOLR_PORT=8983
      #Create the default alfresco and archive cores
      - SOLR_CREATE_ALFRESCO_DEFAULTS=alfresco,archive
    ports:
      - 8983 #Browser port

  activemq:
    image: ${ACTIVEMQ_IMAGE}:${ACTIVEMQ_TAG}
    ports:
      - 8161:8161 # Web Console
      - 5672:5672 # AMQP
      - 61616:61616 # OpenWire
      - 61613:61613 # STOMP