FROM ${ALFRESCO_IMAGE}

ENV TOMCAT_DIR=/usr/local/tomcat
ENV ALF_DATA_DIR=$${TOMCAT_DIR}/alf_data

# COMMS
ARG SOLR_COMMS
ENV SOLR_COMMS $$SOLR_COMMS

# SSL
ARG TRUSTSTORE_TYPE
ARG TRUSTSTORE_PASS
ARG KEYSTORE_TYPE
ARG KEYSTORE_PASS

ENV TRUSTSTORE_TYPE=$$TRUSTSTORE_TYPE \
    TRUSTSTORE_PASS=$$TRUSTSTORE_PASS \
    KEYSTORE_TYPE=$$KEYSTORE_TYPE \
    KEYSTORE_PASS=$$KEYSTORE_PASS

USER root

# Default value in 'repository.properties' is 'dir.keystore=classpath:alfresco/keystore'
RUN if [ "$$SOLR_COMMS" == "https" ] ; then \
        echo -e "\n\
        dir.keystore=$${ALF_DATA_DIR}/keystore\n\
        alfresco.encryption.ssl.keystore.type=$${TRUSTSTORE_TYPE}\n\
        alfresco.encryption.ssl.truststore.type=$${KEYSTORE_TYPE}\n\
        " >> $${TOMCAT_DIR}/shared/classes/alfresco-global.properties; \
    fi

# Enable SSL by adding the proper Connector to server.xml
RUN if [ "$$SOLR_COMMS" == "https" ] ; then \
      sed -i "s/\
[[:space:]]\+<\/Engine>/\n\
        <\/Engine>\n\
        <Connector port=\"8443\" protocol=\"org.apache.coyote.http11.Http11Protocol\"\n\
            connectionTimeout=\"20000\"\n\
            SSLEnabled=\"true\" maxThreads=\"150\" scheme=\"https\"\n\
            keystoreFile=\"\/usr\/local\/tomcat\/alf_data\/keystore\/ssl.keystore\"\n\
            keystorePass=\"$${KEYSTORE_PASS}\" keystoreType=\"$${KEYSTORE_TYPE}\" secure=\"true\"\n\
            truststoreFile=\"\/usr\/local\/tomcat\/alf_data\/keystore\/ssl.truststore\"\n\
            truststorePass=\"$${TRUSTSTORE_PASS}\" truststoreType=\"$${TRUSTSTORE_TYPE}\" clientAuth=\"want\" sslProtocol=\"TLS\">\n\
        <\/Connector>/g" $${TOMCAT_DIR}/conf/server.xml; \
    elif [ "$$SOLR_COMMS" == "none" ] ; then \
      sed -i "s/<filter-class>org.alfresco.web.app.servlet.AlfrescoX509ServletFilter<\/filter-class>/&\n\
        <init-param>\n\
           <param-name>allow-unauthenticated-solr-endpoint<\/param-name>\n\
           <param-value>true<\/param-value>\n\
        <\/init-param>/" $${TOMCAT_DIR}/webapps/alfresco/WEB-INF/web.xml; \
    fi

# Expose keystore folder
# Useless for 'none'/'http' communications with SOLR
VOLUME ["$$ALF_DATA_DIR/keystore"]
