# Using version 2 as 3 does not support resource constraint options (cpu_*, mem_* limits) for non swarm mode in Compose
version: "2"

services:
    alfresco:
        build:
          context: ./alfresco
          args:
            ALFRESCO_TAG: ${ALFRESCO_TAG}
            SOLR_COMMS: <%=secureComms%> <% if (httpMode == 'https') { %>
            TRUSTSTORE_TYPE: JCEKS
            TRUSTSTORE_PASS: kT9X6oe68t
            KEYSTORE_TYPE: JCEKS
            KEYSTORE_PASS: kT9X6oe68t <% } %>
            COMPRESS_CONTENT: "<%=gzip%>"
        mem_limit: 1800m
        environment:
            JAVA_TOOL_OPTIONS: "
                -Dmetadata-keystore.password=mp6yc0UD9e
                -Dmetadata-keystore.aliases=metadata
                -Dmetadata-keystore.metadata.password=mp6yc0UD9e
                -Dmetadata-keystore.metadata.algorithm=AES            
                <% if (httpMode == 'https') { %>
                -Dencryption.keystore.type=pkcs12 
                -Dencryption.cipherAlgorithm=AES/CBC/PKCS5Padding
                -Dencryption.keyAlgorithm=AES
                -Dssl-keystore.password=kT9X6oe68t
                -Dssl-keystore.aliases=ssl-alfresco-ca,ssl-repo
                -Dssl-keystore.ssl-alfresco-ca.password=kT9X6oe68t
                -Dssl-keystore.ssl-repo.password=kT9X6oe68t
                -Dssl-truststore.password=kT9X6oe68t 
                -Dssl-truststore.aliases=alfresco-ca,ssl-repo-client
                -Dssl-truststore.alfresco-ca.password=kT9X6oe68t
                -Dssl-truststore.ssl-repo-client.password=kT9X6oe68t <% } %>
            "
            JAVA_OPTS: "
                -Ddb.driver=org.postgresql.Driver
                -Ddb.username=alfresco
                -Ddb.password=alfresco
                -Ddb.url=jdbc:postgresql://postgres:5432/alfresco
                -Dsolr.host=<%=searchSolrHost%>
                -Dsolr.port.ssl=8983
                -Dsolr.secureComms=<%=secureComms%>
                -Dsolr.baseUrl=/solr <% if (sharding == 'true') { %>
                -Dsolr.useDynamicShardRegistration=true <% } %>
                -Dindex.subsystem.name=solr6
                
                -Daos.baseUrlOverwrite=http://localhost:8080/alfresco/aos
                -Dmessaging.broker.url=\"failover:(nio://activemq:61616)?timeout=3000&jms.useCompression=true\"
                -Ddeployment.method=DOCKER_COMPOSE

                -Dtransform.service.enabled=true
                -Dtransform.service.url=http://transform-router:8095
                -Dsfs.url=http://shared-file-store:8099/
                -DlocalTransform.core-aio.url=http://transform-core-aio:8090/
                -Dalfresco-pdf-renderer.url=http://transform-core-aio:8090/
                -Djodconverter.url=http://transform-core-aio:8090/
                -Dimg.url=http://transform-core-aio:8090/
                -Dtika.url=http://transform-core-aio:8090/
                -Dtransform.misc.url=http://transform-core-aio:8090/

                -Dcsrf.filter.enabled=false
                -Dalfresco.restApi.basicAuthScheme=true
                -Xms1500m -Xmx1500m
                " <% if (httpMode == 'https') { %>
        ports:
            - 8443:8443
        volumes:
            - ./keystores/alfresco:/usr/local/tomcat/alf_data/keystore <% } %>

    solr6:
        build:
          context: ./search
          args:
            SEARCH_TAG: ${SEARCH_TAG}
            SOLR_HOSTNAME: solr6
            ALFRESCO_HOSTNAME: alfresco
            ALFRESCO_COMMS: <%=secureComms%> <% if (httpMode == 'https') { %>
            TRUSTSTORE_TYPE: JCEKS
            KEYSTORE_TYPE: JCEKS 
            PASSWORDS_AS_ENV_VARS: "true" <% } %> <% if (replication) { %>
            ENABLE_MASTER: "true"
            ENABLE_SLAVE: "false" <% } %> <% if (sharding == 'true') { %>
            ENABLE_SHARDING: "true"
            NUM_SHARDS: "2"
            SHARD_ID: "0" <% if (shardingMethod == 'DB_ID_RANGE') { %>
            SHARD_RANGE: "0-800" <% } %> <% if (shardingMethod == 'DATE') { %>
            SHARD_KEY: "cm:created"
            SHARD_DATE_GROUPING: "2" <% } %> <% if (shardingMethod == 'PROPERTY') { %>
            SHARD_KEY: "shard:shardId" <% } %> <% if (shardingMethod == 'EXPLICIT_ID' || shardingMethod == 'EXPLICIT_ID_FALLBACK_LRIS') { %>
            SHARD_KEY: "shard:shardId" <% } %>
            SHARDING_METHOD: <%=shardingMethod%> <% } %>
            COMPRESS_CONTENT: "<%=gzip%>"
        mem_limit: 1200m
        environment:
            #Solr needs to know how to register itself with Alfresco
            SOLR_ALFRESCO_HOST: "alfresco"
            SOLR_ALFRESCO_PORT: "<%=alfrescoPort%>"
            ALFRESCO_SECURE_COMMS: <%=secureComms%>
            #Alfresco needs to know how to call solr
            SOLR_SOLR_HOST: "solr6"
            SOLR_SOLR_PORT: "8983"
            #Create the default alfresco and archive cores
            SOLR_CREATE_ALFRESCO_DEFAULTS: "alfresco,archive"
            SOLR_JAVA_MEM: "-Xms1g -Xmx1g" <% if (httpMode == 'https') { %>
            SOLR_SSL_TRUST_STORE: "/opt/<%=searchPath%>/keystore/ssl-repo-client.truststore"
            SOLR_SSL_TRUST_STORE_TYPE: "JCEKS"
            SOLR_SSL_KEY_STORE: "/opt/<%=searchPath%>/keystore/ssl-repo-client.keystore"
            SOLR_SSL_KEY_STORE_TYPE: "JCEKS"
            SOLR_SSL_NEED_CLIENT_AUTH: "true" <% if (sharding == 'true') { %>
            SOLR_SSL_CLIENT_KEY_STORE: "/opt/<%=searchPath%>/keystore/ssl-repo-client.keystore"
            SOLR_SSL_CLIENT_KEY_STORE_TYPE: "JCEKS"
            SOLR_SSL_CLIENT_TRUST_STORE: "/opt/<%=searchPath%>/keystore/ssl-repo-client.keystore"
            SOLR_SSL_CLIENT_TRUST_STORE_TYPE: "JCEKS" <% } %>
            JAVA_TOOL_OPTIONS: "
                -Dsolr.jetty.truststore.password=kT9X6oe68t
                -Dsolr.jetty.keystore.password=kT9X6oe68t <% if (sharding == 'true') { %>
                -Djavax.net.ssl.keyStorePassword=kT9X6oe68t
                -Djavax.net.ssl.trustStorePassword=kT9X6oe68t <% } %>
                -Dssl-keystore.password=kT9X6oe68t
                -Dssl-keystore.aliases=ssl-alfresco-ca,ssl-repo-client
                -Dssl-keystore.ssl-alfresco-ca.password=kT9X6oe68t
                -Dssl-keystore.ssl-repo-client.password=kT9X6oe68t
                -Dssl-truststore.password=kT9X6oe68t
                -Dssl-truststore.aliases=ssl-alfresco-ca,ssl-repo,ssl-repo-client
                -Dssl-truststore.ssl-alfresco-ca.password=kT9X6oe68t
                -Dssl-truststore.ssl-repo.password=kT9X6oe68t
                -Dssl-truststore.ssl-repo-client.password=kT9X6oe68t      
            "
            SOLR_OPTS: "
                -Dsolr.ssl.checkPeerName=false
                -Dsolr.allow.unsafe.resourceloading=true
            " <% } %>
        ports:
            - 8083:8983 <% if (httpMode == 'https') { %>
        volumes:
            - ./keystores/solr:/opt/<%=searchPath%>/keystore <% } %>

    <% if (sharding == 'true' || replication) { %>
    solr6secondary:
        build:
          context: ./search
          args:
            SEARCH_TAG: ${SEARCH_TAG}
            SOLR_HOSTNAME: solr6secondary
            ALFRESCO_HOSTNAME: alfresco
            ALFRESCO_COMMS: <%=secureComms%> <% if (httpMode == 'https') { %>
            TRUSTSTORE_TYPE: JCEKS
            KEYSTORE_TYPE: JCEKS 
            PASSWORDS_AS_ENV_VARS: "true"  <% } %> <% if (replication) { %>
            ENABLE_MASTER: <% if (replication == 'master-master') { %>"true"<% } else { %>"false"<% } %>
            ENABLE_SLAVE: <% if (replication == 'master-master') { %>"false"<% } else { %>"true"<% } %>
            MASTER_HOST: solr6 <% } %> <% if (sharding == 'true') { %>
            ENABLE_SHARDING: "true"
            NUM_SHARDS: "2"
            SHARD_ID: "1" <% if (shardingMethod == 'DB_ID_RANGE') { %>
            SHARD_RANGE: "801-40000" <% } %> <% if (shardingMethod == 'DATE') { %>
            SHARD_KEY: "cm:created"
            SHARD_DATE_GROUPING: "2" <% } %> <% if (shardingMethod == 'PROPERTY') { %>
            SHARD_KEY: "shard:shardId" <% } %> <% if (shardingMethod == 'EXPLICIT_ID' || shardingMethod == 'EXPLICIT_ID_FALLBACK_LRIS') { %>
            SHARD_KEY: "shard:shardId" <% } %>
            SHARDING_METHOD: <%=shardingMethod%> <% } %>
            COMPRESS_CONTENT: "<%=gzip%>"
        mem_limit: 1200m
        environment:
            #Solr needs to know how to register itself with Alfresco
            SOLR_ALFRESCO_HOST: "alfresco"
            SOLR_ALFRESCO_PORT: "<%=alfrescoPort%>"
            ALFRESCO_SECURE_COMMS: <%=secureComms%>
            #Alfresco needs to know how to call solr
            SOLR_SOLR_HOST: "solr6secondary"
            SOLR_SOLR_PORT: "8983"
            #Create the default alfresco and archive cores
            SOLR_CREATE_ALFRESCO_DEFAULTS: "alfresco,archive"
            SOLR_JAVA_MEM: "-Xms1g -Xmx1g" <% if (httpMode == 'https') { %>
            SOLR_SSL_TRUST_STORE: "/opt/<%=searchPath%>/keystore/ssl-repo-client.truststore"
            SOLR_SSL_TRUST_STORE_TYPE: "JCEKS"
            SOLR_SSL_KEY_STORE: "/opt/<%=searchPath%>/keystore/ssl-repo-client.keystore"
            SOLR_SSL_KEY_STORE_TYPE: "JCEKS"
            SOLR_SSL_NEED_CLIENT_AUTH: "true" <% if (sharding == 'true') { %>
            SOLR_SSL_CLIENT_KEY_STORE: "/opt/<%=searchPath%>/keystore/ssl-repo-client.keystore"
            SOLR_SSL_CLIENT_KEY_STORE_TYPE: "JCEKS"
            SOLR_SSL_CLIENT_TRUST_STORE: "/opt/<%=searchPath%>/keystore/ssl-repo-client.keystore"
            SOLR_SSL_CLIENT_TRUST_STORE_TYPE: "JCEKS" <% } %>
            JAVA_TOOL_OPTIONS: "
                -Dsolr.jetty.truststore.password=kT9X6oe68t
                -Dsolr.jetty.keystore.password=kT9X6oe68t <% if (sharding == 'true') { %>
                -Djavax.net.ssl.keyStorePassword=kT9X6oe68t
                -Djavax.net.ssl.trustStorePassword=kT9X6oe68t <% } %>
                -Dssl-keystore.password=kT9X6oe68t
                -Dssl-keystore.aliases=ssl-alfresco-ca,ssl-repo-client
                -Dssl-keystore.ssl-alfresco-ca.password=kT9X6oe68t
                -Dssl-keystore.ssl-repo-client.password=kT9X6oe68t
                -Dssl-truststore.password=kT9X6oe68t
                -Dssl-truststore.aliases=ssl-alfresco-ca,ssl-repo,ssl-repo-client
                -Dssl-truststore.ssl-alfresco-ca.password=kT9X6oe68t
                -Dssl-truststore.ssl-repo.password=kT9X6oe68t
                -Dssl-truststore.ssl-repo-client.password=kT9X6oe68t      
            "
            SOLR_OPTS: "
                -Dsolr.ssl.checkPeerName=false
                -Dsolr.allow.unsafe.resourceloading=true
            " <% } %>
        ports:
            - 8084:8983  <% if (httpMode == 'https') { %>
        volumes:
            - ./keystores/solr:/opt/<%=searchPath%>/keystore <% } %>
    <% } %>

    <% if (zeppelin == 'true') { %>
    zeppelin:
        build:
          context: ./zeppelin
          args:
            ZEPPELIN_TAG: ${ZEPPELIN_TAG}
            ALFRESCO_COMMS: <%=secureComms%>
        mem_limit: 768m
        environment: <% if (httpMode == 'https') { %>
            REPO_PROTOCOL: "https" <% } %>
            REPO_HOST: "alfresco"
            REPO_PORT: "<%=alfrescoPort%>" <% if (httpMode == 'https') { %>
            JAVA_TOOL_OPTIONS: "
                -Djavax.net.ssl.keyStore=/zeppelin/keystore/ssl-repo-client.keystore
                -Djavax.net.ssl.keyStorePassword=kT9X6oe68t
                -Djavax.net.ssl.keyStoreType=JCEKS
                -Djavax.net.ssl.trustStore=/zeppelin/keystore/ssl-repo-client.truststore
                -Djavax.net.ssl.trustStorePassword=kT9X6oe68t
                -Djavax.net.ssl.trustStoreType=JCEKS
            "
            JAVA_OPTS: "
                -Dalfresco.enable.ssl=true
                -Dsolr.ssl.checkPeerName=false
            " <% } %>
        ports:
            - 9090:9090 <% if (httpMode == 'https') { %>
        volumes:
            - ./keystores/zeppelin:/zeppelin/keystore <% } %>
    <% } %>

    transform-router:
        mem_limit: 512m
        image: quay.io/alfresco/alfresco-transform-router:${TRANSFORM_ROUTER_TAG}
        environment:
          JAVA_OPTS: " -Xms256m -Xmx512m"
          ACTIVEMQ_URL: "nio://activemq:61616"
          CORE_AIO_URL : "http://transform-core-aio:8090"
          FILE_STORE_URL: "http://shared-file-store:8099/alfresco/api/-default-/private/sfs/versions/1/file"
        ports:
            - 8095:8095
        links:
          - activemq

    transform-core-aio:
        image: alfresco/alfresco-transform-core-aio:${TRANSFORM_CORE_AIO_TAG}
        mem_limit: 1536m
        environment:
            JAVA_OPTS: " -Xms256m -Xmx1536m"
            ACTIVEMQ_URL: "nio://activemq:61616"
            FILE_STORE_URL: "http://shared-file-store:8099/alfresco/api/-default-/private/sfs/versions/1/file"
        ports:
            - 8090:8090
        links:
        - activemq    

    shared-file-store:
        image: alfresco/alfresco-shared-file-store:${SHARED_FILE_STORE_TAG}
        mem_limit: 512m
        environment:
            JAVA_OPTS: " -Xms256m -Xmx512m"
            scheduler.content.age.millis: 86400000
            scheduler.cleanup.interval: 86400000
        ports:
            - 8099:8099
        volumes:
            - shared-file-store-volume:/tmp/Alfresco/sfs

    share:
        build:
          context: ./share
          args:
            SHARE_TAG: ${SHARE_TAG}
        mem_limit: 1g
        environment:
            REPO_HOST: "alfresco"
            REPO_PORT: "8080"
            JAVA_OPTS: "
                -Xms500m
                -Xmx500m
                -Dalfresco.host=localhost
                -Dalfresco.port=8080
                -Dalfresco.context=alfresco
                -Dalfresco.protocol=http
                "

    postgres:
        image: postgres:${POSTGRES_TAG}
        mem_limit: 512m
        environment:
            - POSTGRES_PASSWORD=alfresco
            - POSTGRES_USER=alfresco
            - POSTGRES_DB=alfresco
        command: postgres -c max_connections=300 -c log_min_messages=LOG
        ports:
            - 5432:5432

    activemq:
        image: alfresco/alfresco-activemq:${ACTIVE_MQ_TAG}
        mem_limit: 1g
        ports:
            - 8161:8161 # Web Console
            - 5672:5672 # AMQP
            - 61616:61616 # OpenWire
            - 61613:61613 # STOMP

    content-app:
        image: quay.io/alfresco/alfresco-digital-workspace:${DIGITAL_WORKSPACE_TAG}
        mem_limit: 128m
        environment:
            BASEPATH: ./

    # HTTP proxy to provide HTTP Default port access to services
    # SOLR API and SOLR Web Console are protected to avoid unauthenticated access
    proxy:
        image: nginx:stable-alpine
        mem_limit: 128m
        depends_on:
            - alfresco
        volumes:
            - ./config/nginx.conf:/etc/nginx/nginx.conf
            - ./config/nginx.htpasswd:/etc/nginx/conf.d/nginx.htpasswd <% if (httpWebMode == 'https') { %>
            - ./config/cert/localhost.cer:/etc/nginx/localhost.cer
            - ./config/cert/localhost.key:/etc/nginx/localhost.key <% } %>
        ports:
            - <%=port%>:<%=port%>  
        links:
            - alfresco
            - share
            - solr6
            - content-app

volumes:
    shared-file-store-volume:
        driver_opts:
            type: tmpfs
            device: tmpfs
