version: '3'
services:
  alfresco:
    image: alfresco/alfresco-content-repository:${ALFRESCO_TAG}
    environment:
      JAVA_OPTS : "
        -Ddb.driver=org.postgresql.Driver
        -Ddb.username=alfresco
        -Ddb.password=alfresco
        -Ddb.url=jdbc:postgresql://postgres:5432/alfresco
        -Dsolr.host=search_slave_load_balancer
        -Dsolr.port=80
        -Dsolr.secureComms=none
        -Dalfresco.restApi.basicAuthScheme=true
        -Dsolr.base.url=/solr
        -Dindex.subsystem.name=solr6
        -Dmessaging.broker.url=\"failover:(nio://activemq:61616)?timeout=3000&jms.useCompression=true\"
        "

  search_slave_load_balancer:
    image: nginx:${NGINX_TAG}
    links:
      - search_slave
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8084:80

  search_slave:
    image: quay.io/alfresco/search-services:${SEARCH_TAG}
    environment:
      #Replication properties
      - REPLICATION_TYPE=slave
      - REPLICATION_MASTER_HOST=search
      - REPLICATION_MASTER_PORT=8983
      #- REPLICATION_MASTER_PROTOCOL=http
      #- REPLICATION_CORE_NAME=alfresco
      #- REPLICATION_POLL_INTERVAL=00:00:60
      #Solr needs to know how to register itself with Alfresco
      - SOLR_ALFRESCO_HOST=alfresco
      - SOLR_ALFRESCO_PORT=8080
      #Alfresco needs to know how to call solr
      - SOLR_SOLR_HOST=search_slave_load_balancer
      - SOLR_SOLR_PORT=80
      #Create the default alfresco and archive cores
      - SOLR_CREATE_ALFRESCO_DEFAULTS=alfresco,archive
    ports:
      - "8983" #Internal port