ARG ALFRESCO_TAG=6.1.0-EA3
FROM quay.io/alfresco/alfresco-content-repository:$ALFRESCO_TAG
LABEL creator="Paul Brodner" maintainer="Alfresco Search Services Team"

COPY 6.1-server.xml /usr/local/tomcat/conf/server.xml
