# Using version 2 as 3 does not support resource constraint options (cpu_*, mem_* limits) for non swarm mode in Compose
version: "2"

services:
    alfresco:
        image: quay.io/alfresco/alfresco-content-repository-52:${ALFRESCO_TAG}
        mem_limit: 2g
        environment:
          MEM_LIMIT: 2200m
          JAVA_TOOL_OPTIONS: "
            -Dsolr.host=search
            -Dsolr.port=8983
            -Dsolr.secureComms=none
            -Dsolr.base.url=/solr
            -Dindex.subsystem.name=solr6
            "
        ports:
          - 7203:7203 #JMX connect via service:jmx:rmi:///jndi/rmi://localhost:7203/jmxrmi
          - 5005:5005 #Java debugging
          - 8081:8080 #Browser port for Alfresco

    share:
        image: quay.io/alfresco/alfresco-share-52:${SHARE_TAG}
        mem_limit: 1g
        environment:
          MEM_LIMIT: 1200m
        ports:
          - 8082:8080

    search:
      image: quay.io/alfresco/search-services:${SEARCH_TAG}
      environment:
        #Solr needs to know how to register itself with Alfresco
        SOLR_ALFRESCO_HOST: alfresco
        SOLR_ALFRESCO_PORT: 8080
        #Alfresco needs to know how to call solr
        SOLR_SOLR_HOST: search
        SOLR_SOLR_PORT: 8983
        #Create the default alfresco and archive cores
        SOLR_CREATE_ALFRESCO_DEFAULTS: alfresco,archive
        #HTTP by default
        ALFRESCO_SECURE_COMMS: none
      ports:
        - 8083:8983

    libreoffice:
        image: xcgd/libreoffice
        mem_limit: 1g

    postgres:
        image: postgres:${POSTGRES_TAG}
        mem_limit: 512m
        environment:
            - POSTGRES_PASSWORD=alfresco
            - POSTGRES_USER=alfresco
            - POSTGRES_DB=alfresco
        command: postgres -c max_connections=300 -c log_min_messages=LOG
        ports:
            - 5432:5432
